export const RECEIVE_TASKLISTS = 'RECEIVE_TASKLISTS';
export const RECEIVE_TASKLIST = 'RECEIVE_TASKLIST';

export const DELETE_TASKLIST = 'DELETE_TASKLIST';
export const RENAME_TASKLIST = 'EDIT_TASKLIST';

export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const RECEIVE_TASK = 'RECEIVE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_SCREEN = 'SET_SCREEN';

export const RECEIVE_AVATAR_URL = 'RECEIVE_AVATAR_URL';

export const START_PROGRESS = 'START_PROGRESS';
export const FINISH_PROGRESS = 'FINISH_PROGRESS';

export const SELECT_TASKLIST = 'SELECT_TASKLIST';

export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';
export const RESET_AUTHORIZATION = 'RESET_AUTHORIZATION';

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';