export const RECEIVE_TASKLISTS = 'RECEIVE_TASKLISTS';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_SCREEN = 'SET_SCREEN';

export const RECEIVE_AVATAR_URL = 'RECEIVE_AVATAR_URL';

export const START_PROGRESS = 'START_PROGRESS';
export const FINISH_PROGRESS = 'FINISH_PROGRESS';

export const SELECT_TASKLIST = 'SELECT_TASKLIST';